'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Check, ChevronDown, Heart, Menu, Minus, Plus, Search, ShoppingBag, Sparkles, Star, X } from 'lucide-react'

const images = {
  hero: '/images/aurelia-hero.png',
  espresso: '/images/aurelia-coffee.png',
  latte: '/images/aurelia-coffee.png',
  pastry: '/images/aurelia-pastry.png',
  brunch: '/images/aurelia-brunch.png',
  interior: '/images/aurelia-gallery.png',
  pour: '/images/aurelia-coffee.png',
  beans: '/images/aurelia-pastry.png',
  people: '/images/aurelia-gallery.png',
}

const products = [
  { name: 'Signature Espresso', category: 'Coffee', price: 4.5, description: 'A bright, balanced house blend with notes of cacao.', image: images.espresso, tag: 'House classic' },
  { name: 'Vanilla Bean Latte', category: 'Coffee', price: 6.5, description: 'Velvety espresso, steamed milk, and real vanilla bean.', image: images.latte, tag: 'Most loved' },
  { name: 'Pistachio Croissant', category: 'Bakery', price: 5.75, description: 'Twice-baked pastry with pistachio frangipane.', image: images.pastry, tag: 'Baked today' },
  { name: 'AURELIA Breakfast', category: 'Breakfast', price: 14, description: 'Soft eggs, sourdough, greens, and seasonal preserves.', image: images.brunch, tag: 'Seasonal' },
]
const categories = ['All', 'Coffee', 'Tea', 'Breakfast', 'Bakery', 'Desserts']
type Product = typeof products[number]

export default function Home() {
  const [activeCategory, setActiveCategory] = useState('All')
  const [favorites, setFavorites] = useState<string[]>([])
  const [cart, setCart] = useState<Product[]>([])
  const [cartOpen, setCartOpen] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [reservationSent, setReservationSent] = useState(false)
  const [subscribed, setSubscribed] = useState(false)
  const [search, setSearch] = useState('')
  const filteredProducts = useMemo(() => products.filter((product) => (activeCategory === 'All' || product.category === activeCategory) && product.name.toLowerCase().includes(search.toLowerCase())), [activeCategory, search])
  const addToCart = (product: Product) => { setCart((current) => [...current, product]); setCartOpen(true) }
  const toggleFavorite = (name: string) => setFavorites((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name])

  return (
    <main className="min-h-screen overflow-hidden bg-background text-foreground">
      <header className="absolute inset-x-0 top-0 z-30 border-b border-white/20 text-white"><div className="mx-auto flex max-w-[1400px] items-center justify-between px-5 py-5 lg:px-10"><a href="#top" className="font-serif text-2xl tracking-[0.18em]">AURELIA</a><nav className="hidden items-center gap-8 text-xs uppercase tracking-[0.18em] lg:flex" aria-label="Main navigation"><a href="#menu">Menu</a><a href="#story">Our Story</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a></nav><div className="flex items-center gap-3"><button onClick={() => setCartOpen(true)} className="relative rounded-full border border-white/40 p-2.5 transition hover:bg-white hover:text-foreground" aria-label={`Open order, ${cart.length} items`}><ShoppingBag size={17}/>{cart.length > 0 && <span className="absolute -right-1 -top-1 flex size-4 items-center justify-center rounded-full bg-accent text-[9px] text-accent-foreground">{cart.length}</span>}</button><a href="#reserve" className="hidden rounded-full bg-white px-5 py-3 text-xs font-semibold uppercase tracking-[0.12em] text-foreground transition hover:bg-accent lg:block">Reserve a Table</a><button onClick={() => setMenuOpen(!menuOpen)} className="rounded-full border border-white/40 p-2.5 lg:hidden" aria-label="Toggle menu">{menuOpen ? <X size={17}/> : <Menu size={17}/>}</button></div></div>{menuOpen && <nav className="flex flex-col gap-5 bg-foreground px-6 py-6 text-sm uppercase tracking-[0.14em] lg:hidden"><a href="#menu">Menu</a><a href="#story">Our Story</a><a href="#gallery">Gallery</a><a href="#reserve">Reserve a Table</a></nav>}</header>
      <section id="top" className="relative flex min-h-[720px] items-end bg-cover bg-center px-5 pb-14 pt-32 text-white lg:min-h-[850px] lg:px-10 lg:pb-20" style={{ backgroundImage: `linear-gradient(90deg, rgba(21,15,12,.7), rgba(21,15,12,.12)), url(${images.hero})` }}><div className="mx-auto flex w-full max-w-[1400px] items-end justify-between gap-8"><div className="max-w-3xl"><p className="eyebrow mb-7 text-white/75">Specialty coffee · Since 2018</p><h1 className="max-w-4xl font-serif text-6xl leading-[.9] tracking-[-0.05em] sm:text-8xl lg:text-[9.5rem]">Crafted Slowly.<br/><em className="text-accent">Enjoyed Fully.</em></h1><p className="mt-8 max-w-md text-base leading-relaxed text-white/80">Specialty coffee, seasonal plates, and quiet moments in the heart of the city.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#menu" className="rounded-full bg-accent px-7 py-4 text-xs font-semibold uppercase tracking-[0.15em] text-accent-foreground transition hover:-translate-y-1">Explore Menu <ArrowRight className="ml-2 inline" size={15}/></a><a href="#reserve" className="rounded-full border border-white/40 px-7 py-4 text-xs font-semibold uppercase tracking-[0.15em] transition hover:bg-white hover:text-foreground">Reserve a Table</a></div></div><div className="hidden border-l border-white/40 pl-5 text-xs leading-relaxed text-white/75 md:block"><span className="mb-2 block size-2 rounded-full bg-accent"/>Open daily<br/>07:00 — 21:00<br/><br/>14 Mercer Street<br/>New York, NY</div></div></section>
      <section className="mx-auto max-w-[1400px] px-5 py-24 lg:px-10 lg:py-32"><div className="mb-10 flex items-end justify-between gap-4"><div><p className="eyebrow">The daily edit</p><h2 className="section-title">Made for your<br/><em>daily ritual.</em></h2></div><a href="#menu" className="hidden items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] md:flex">View full menu <ArrowRight size={16}/></a></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map((product) => <ProductCard key={product.name} product={product} favorite={favorites.includes(product.name)} onFavorite={() => toggleFavorite(product.name)} onAdd={() => addToCart(product)}/>)}</div></section>
      <section id="story" className="bg-secondary"><div className="mx-auto grid max-w-[1400px] gap-12 px-5 py-24 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:gap-24 lg:px-10 lg:py-32"><div className="relative"><img src={images.interior} alt="Warmly lit AURELIA café interior" className="aspect-[4/5] w-full object-cover"/><div className="absolute -bottom-5 -right-3 bg-accent px-5 py-4 text-xs uppercase tracking-[0.14em] text-accent-foreground lg:-right-8"><span className="font-serif text-2xl">01</span> / 04<br/>The space</div></div><div className="max-w-xl"><p className="eyebrow">Our point of view</p><h2 className="section-title">Coffee with a<br/><em>point of view.</em></h2><p className="mt-8 text-base leading-8 text-muted-foreground">AURELIA is a neighborhood coffee house built around the belief that the everyday deserves attention. We source expressive beans, partner with local producers, and make every plate and pour with intention.</p><p className="mt-5 text-base leading-8 text-muted-foreground">Come for the coffee. Stay for the feeling of having nowhere else to be.</p><a href="#gallery" className="mt-9 inline-flex items-center gap-3 border-b border-foreground pb-3 text-xs font-semibold uppercase tracking-[0.15em]">Discover our story <ArrowRight size={15}/></a></div></div></section>
      <section className="mx-auto max-w-[1400px] px-5 py-24 lg:px-10 lg:py-32"><div className="grid gap-5 lg:grid-cols-12"><div className="relative min-h-[520px] overflow-hidden bg-cover bg-center lg:col-span-7" style={{ backgroundImage: `url(${images.pour})` }}><div className="absolute inset-0 bg-gradient-to-t from-foreground/70 to-transparent"/><div className="absolute bottom-7 left-7 text-white"><p className="eyebrow text-white/70">01 · Morning</p><h3 className="font-serif text-5xl">Begin gently.</h3></div></div><div className="grid gap-5 lg:col-span-5"><div className="relative min-h-[250px] overflow-hidden bg-cover bg-center" style={{ backgroundImage: `url(${images.beans})` }}><div className="absolute inset-0 bg-foreground/35"/><h3 className="absolute bottom-6 left-6 font-serif text-4xl text-white">Roasted with care.</h3></div><div className="flex min-h-[250px] flex-col justify-between bg-accent p-7 text-accent-foreground"><Sparkles size={22}/><div><p className="eyebrow text-accent-foreground/70">The AURELIA experience</p><h3 className="font-serif text-4xl leading-tight">A little more<br/><em>beautiful.</em></h3></div></div></div></div></section>
      <section id="menu" className="bg-foreground text-background"><div className="mx-auto max-w-[1400px] px-5 py-24 lg:px-10 lg:py-32"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow text-accent">From the counter</p><h2 className="section-title">The menu.</h2></div><div className="relative flex items-center border-b border-background/30 pb-3 md:w-64"><Search size={16} className="mr-3 text-background/60"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search the menu" className="w-full bg-transparent text-sm outline-none placeholder:text-background/45" aria-label="Search menu"/></div></div><div className="my-10 flex gap-2 overflow-x-auto border-y border-background/20 py-4">{categories.map((category) => <button key={category} onClick={() => setActiveCategory(category)} className={`whitespace-nowrap rounded-full px-5 py-2.5 text-xs uppercase tracking-[0.12em] transition ${activeCategory === category ? 'bg-accent text-accent-foreground' : 'text-background/65 hover:text-background'}`}>{category}</button>)}</div><div className="grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{filteredProducts.map((product) => <ProductCard key={product.name} product={product} dark favorite={favorites.includes(product.name)} onFavorite={() => toggleFavorite(product.name)} onAdd={() => addToCart(product)}/>)}</div>{filteredProducts.length === 0 && <p className="py-16 text-center text-background/60">Nothing on the menu matches that search.</p>}</div></section>
      <section id="gallery" className="mx-auto max-w-[1400px] px-5 py-24 lg:px-10 lg:py-32"><div className="mb-12 flex items-end justify-between"><div><p className="eyebrow">A place to linger</p><h2 className="section-title">Inside<br/><em>AURELIA.</em></h2></div><p className="hidden max-w-xs text-sm leading-7 text-muted-foreground md:block">A café for first dates, last pages, and the space between.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:grid-rows-2"><img src={images.people} alt="Friends enjoying coffee together" className="aspect-square w-full object-cover md:col-span-2 md:row-span-2 md:aspect-auto"/><img src={images.latte} alt="Latte art in a ceramic cup" className="aspect-square w-full object-cover"/><img src={images.pastry} alt="Fresh pastries on a counter" className="aspect-square w-full object-cover"/><img src={images.interior} alt="AURELIA interior details" className="aspect-square w-full object-cover"/><div className="flex aspect-square flex-col justify-between bg-accent p-5 text-accent-foreground md:p-7"><Star size={20} fill="currentColor"/><p className="font-serif text-2xl leading-tight">“Every detail feels intentional.”</p><span className="text-xs uppercase tracking-[0.14em]">— Sofia R.</span></div></div></section>
      <section id="reserve" className="bg-secondary"><div className="mx-auto grid max-w-[1400px] gap-12 px-5 py-24 lg:grid-cols-[.8fr_1.2fr] lg:gap-24 lg:px-10 lg:py-32"><div><p className="eyebrow">Make a moment of it</p><h2 className="section-title">Reserve<br/><em>your table.</em></h2><p className="mt-7 max-w-sm leading-7 text-muted-foreground">Whether it is a quiet breakfast or a long overdue catch-up, we will keep a seat warm for you.</p><div className="mt-10 text-sm leading-7 text-muted-foreground">14 Mercer Street, New York<br/>Monday — Sunday, 07:00 — 21:00<br/>+1 212 555 0148</div></div><form onSubmit={(e) => {e.preventDefault(); setReservationSent(true)}} className="grid gap-5 sm:grid-cols-2">{['Name','Email','Date','Time'].map((label) => <label key={label} className="field-label">{label}<input required type={label === 'Email' ? 'email' : label === 'Date' ? 'date' : label === 'Time' ? 'time' : 'text'} className="field-input"/></label>)}<label className="field-label">Guests<select className="field-input"><option>2 guests</option><option>3 guests</option><option>4 guests</option><option>5+ guests</option></select><ChevronDown className="pointer-events-none relative float-right -mt-9 mr-3" size={16}/></label><label className="field-label">Special request<input className="field-input" placeholder="Optional"/></label><button className="sm:col-span-2 rounded-full bg-foreground px-7 py-4 text-xs font-semibold uppercase tracking-[0.15em] text-background transition hover:bg-accent hover:text-accent-foreground">{reservationSent ? <><Check className="mr-2 inline" size={15}/> Request received</> : 'Reserve your table'}</button></form></div></section>
      <section className="bg-accent px-5 py-20 text-center text-accent-foreground lg:px-10"><p className="eyebrow">A note from the house</p><h2 className="mx-auto max-w-2xl font-serif text-5xl leading-[.95] tracking-tight sm:text-7xl">Stay in the<br/><em>AURELIA circle.</em></h2><p className="mx-auto mt-6 max-w-md text-sm leading-6 text-accent-foreground/75">Seasonal menus, new beans, and good things worth knowing.</p><form onSubmit={(e) => {e.preventDefault(); setSubscribed(true)}} className="mx-auto mt-8 flex max-w-md border-b border-accent-foreground/50 pb-3"><input required type="email" placeholder="Your email address" className="w-full bg-transparent text-sm outline-none placeholder:text-accent-foreground/60"/><button className="text-xs font-semibold uppercase tracking-[0.12em]">{subscribed ? 'Thank you' : 'Subscribe'}</button></form></section>
      <footer id="contact" className="bg-foreground px-5 py-14 text-background lg:px-10"><div className="mx-auto grid max-w-[1400px] gap-12 md:grid-cols-4"><div className="md:col-span-2"><div className="font-serif text-3xl tracking-[0.18em]">AURELIA</div><p className="mt-5 max-w-xs text-sm leading-7 text-background/60">A neighborhood coffee house for exceptional coffee, good food, and unhurried moments.</p></div><div><p className="eyebrow text-accent">Explore</p><div className="flex flex-col gap-3 text-sm text-background/70"><a href="#menu">Menu</a><a href="#story">Our Story</a><a href="#gallery">Gallery</a><a href="#reserve">Reservations</a></div></div><div><p className="eyebrow text-accent">Find us</p><p className="text-sm leading-7 text-background/70">14 Mercer Street<br/>New York, NY 10013<br/><br/>hello@aurelia.coffee<br/>Instagram ↗</p></div></div><div className="mx-auto mt-16 flex max-w-[1400px] justify-between border-t border-background/15 pt-6 text-xs text-background/40"><span>© 2024 AURELIA Coffee House</span><span>Privacy · Terms</span></div></footer>
      {cartOpen && <div className="fixed inset-0 z-50 bg-foreground/40" onClick={() => setCartOpen(false)}><aside className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-background p-6 text-foreground shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between border-b border-border pb-5"><div><p className="eyebrow">Your order</p><h2 className="font-serif text-3xl">The bag <span className="text-muted-foreground">({cart.length})</span></h2></div><button onClick={() => setCartOpen(false)} className="rounded-full border p-2" aria-label="Close cart"><X size={18}/></button></div><div className="flex-1 overflow-auto py-5">{cart.length === 0 ? <div className="flex h-full flex-col items-center justify-center text-center"><ShoppingBag className="mb-4 text-muted-foreground" size={32}/><p className="font-serif text-2xl">Your bag is waiting.</p><p className="mt-2 text-sm text-muted-foreground">Add something delicious from the menu.</p></div> : <div className="flex flex-col gap-5">{cart.map((item, index) => <div key={`${item.name}-${index}`} className="flex gap-4"><img src={item.image} alt="" className="size-20 object-cover"/><div className="flex-1"><div className="flex justify-between gap-3"><p className="font-serif text-lg">{item.name}</p><span className="text-sm">${item.price.toFixed(2)}</span></div><p className="mt-1 text-xs text-muted-foreground">Regular · Made to order</p><div className="mt-3 flex items-center gap-3 text-xs"><button className="rounded-full border p-1"><Minus size={12}/></button><span>1</span><button className="rounded-full border p-1"><Plus size={12}/></button></div></div></div>)}</div>}</div>{cart.length > 0 && <div className="border-t border-border pt-5"><div className="flex justify-between text-sm"><span>Subtotal</span><span>${cart.reduce((sum, item) => sum + item.price, 0).toFixed(2)}</span></div><button className="mt-5 w-full rounded-full bg-foreground px-6 py-4 text-xs font-semibold uppercase tracking-[0.15em] text-background">Continue to checkout <ArrowRight className="ml-2 inline" size={15}/></button></div>}</aside></div>}
    </main>
  )
}

function ProductCard({ product, favorite, onFavorite, onAdd, dark = false }: { product: Product, favorite: boolean, onFavorite: () => void, onAdd: () => void, dark?: boolean }) {
  return <article className="group"><div className="relative overflow-hidden"><img src={product.image} alt={product.name} className="aspect-[.9] w-full object-cover transition duration-700 group-hover:scale-105"/><span className="absolute left-4 top-4 bg-accent px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-accent-foreground">{product.tag}</span><button onClick={onFavorite} className="absolute right-4 top-4 rounded-full bg-background/85 p-2.5 text-foreground transition hover:bg-accent" aria-label={`${favorite ? 'Remove' : 'Add'} ${product.name} ${favorite ? 'from' : 'to'} favorites`}><Heart size={15} fill={favorite ? 'currentColor' : 'none'}/></button></div><div className="pt-4"><div className="flex items-start justify-between gap-3"><h3 className={`font-serif text-2xl ${dark ? 'text-background' : ''}`}>{product.name}</h3><span className={`pt-1 text-sm ${dark ? 'text-background/80' : 'text-muted-foreground'}`}>${product.price.toFixed(2)}</span></div><p className={`mt-2 text-sm leading-6 ${dark ? 'text-background/55' : 'text-muted-foreground'}`}>{product.description}</p><button onClick={onAdd} className={`mt-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.12em] ${dark ? 'text-accent' : ''}`}>Add to order <Plus size={15}/></button></div></article>
}
